// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDnD8KcEFRD6nOfGIv6wM_y5EWOOwZHaj8",
      authDomain: "fit-app-db.firebaseapp.com",
      projectId: "fit-app-db",
      storageBucket: "fit-app-db.appspot.com",
      messagingSenderId: "758408692884",
      appId: "1:758408692884:web:fdb74255a5a7f01b712081");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQtcfHz54NFqmOc949MYjoHWAJTK_574Q', //
    appId: '1:758408692884:android:b97538b8330e6123712081', //
    messagingSenderId: '758408692884', //
    projectId: 'fit-app-db', //
    storageBucket: 'fit-app-db.appspot.com', //
  );
}
